//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euclid.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Euclid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body 
        ///{
        ///	font-family: Verdana, Arial, Times New Roman;
        ///	font-size: 14pt;
        ///}
        ///
        ///h1, h2
        ///{
        ///	text-align: center;
        ///}
        ///
        ///h1 
        ///{
        ///	font-size: 21pt;
        ///	color: navy;
        ///}
        ///	
        ///#footer
        ///{
        ///	text-align: center;
        ///	font-size: 10pt;
        ///	font-weight: bold;
        ///	color: grey;
        ///}
        ///.
        /// </summary>
        internal static string css_style {
            get {
                return ResourceManager.GetString("css_style", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap euclid {
            get {
                object obj = ResourceManager.GetObject("euclid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/table&gt;
        ///&lt;div id=&quot;footer&quot;&gt; Generated by {0} v. {1} &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string html_bottom {
            get {
                return ResourceManager.GetString("html_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot; lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;title&gt;Euclid# construction report - {0}&lt;/title&gt;
        ///  &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;{1}/style.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt; {0} &lt;/h1&gt;
        ///&lt;table id=&quot;maintbl&quot;&gt;
        ///.
        /// </summary>
        internal static string html_top {
            get {
                return ResourceManager.GetString("html_top", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap matrix {
            get {
                object obj = ResourceManager.GetObject("matrix", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap norris {
            get {
                object obj = ResourceManager.GetObject("norris", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap norris2 {
            get {
                object obj = ResourceManager.GetObject("norris2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///&lt;td class=&quot;step&quot;&gt;
        ///{0}
        ///&lt;/td&gt;
        ///&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string step {
            get {
                return ResourceManager.GetString("step", resourceCulture);
            }
        }
    }
}
